---
- name: "Application / KeePassX / Setup / User / Configuration repository ({{
    app_keepassx___setup_user['home'] + '/' + app_keepassx_base['paths']['etc_keepassx']
    }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ app_keepassx___setup_user['home'] + '/' + app_keepassx_base['paths']['etc_keepassx'] }}"
    owner: "{{ app_keepassx___setup_user['user'] }}"
    group: "{{ app_keepassx___setup_user['user'] }}"
    mode: "{{ app_keepassx_base['access']['mode']['dir'] }}"

- name: "Application / KeePassX / Setup / User / Create default configuration ({{
    app_keepassx___setup_user['home'] + '/' + app_keepassx_base['etc']['keepassx_ini'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ app_keepassx___setup_user['user'] }}"
    group: "{{ app_keepassx___setup_user['user'] }}"
    mode: "{{ app_keepassx_base['access']['mode']['file'] }}"
    src: "{{ app_keepassx_base['templates']['keepassx_ini'] }}"
    dest: "{{ app_keepassx___setup_user['home'] + '/' + app_keepassx_base['etc']['keepassx_ini'] }}"
...
