---
- name: "Manage Test Nodes"
  hosts: "test_nodes"
  gather_facts: false

  pre_tasks:
    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare package repositories"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"

  tasks:
    - name: "Provision Bats Core"
      vars:
        dops_batscore:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_batscore"
      when:
        - test_nodes_apps['batscore'] is defined
        - test_nodes_apps['batscore']
...
