---
- name: "Manage Office Nodes"
  hosts: "office_nodes"
  gather_facts: false

  pre_tasks:
    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare package repositories"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"

  tasks:

    - name: "Provision Darktable application"
      vars:
        app_darktable:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_darktable"
      when:
        - office_nodes_apps['darktable'] is defined
        - office_nodes_apps['darktable']

    - name: "Provision DrawIO application"
      vars:
        app_drawio:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_drawio"
      when:
        - office_nodes_apps['drawio'] is defined
        - office_nodes_apps['drawio']

    - name: "Provision Google Chrome application"
      vars:
        app_chrome:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_chrome"
      when:
        - office_nodes_apps['chrome'] is defined
        - office_nodes_apps['chrome']

    - name: "Provision GIMP application"
      vars:
        app_gimp:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_gimp"
      when:
        - office_nodes_apps['gimp'] is defined
        - office_nodes_apps['gimp']

    - name: "Provision InkScape application"
      vars:
        app_inkscape:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_inkscape"
      when:
        - office_nodes_apps['inkscape'] is defined
        - office_nodes_apps['inkscape']

    - name: "Provision KeePassXC application"
      vars:
        app_keepassxc:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_keepassxc"
      when:
        - office_nodes_apps['keepassxc'] is defined
        - office_nodes_apps['keepassxc']

    - name: "Provision Kryta application"
      vars:
        app_kryta:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_kryta"
      when:
        - office_nodes_apps['kryta'] is defined
        - office_nodes_apps['kryta']

    - name: "Provision LibreOffice application"
      vars:
        app_libreoffice:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_libreoffice"
      when:
        - office_nodes_apps['libreoffice'] is defined
        - office_nodes_apps['libreoffice']

    - name: "Provision MS Teams application"
      vars:
        app_msteams:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_msteams"
      when:
        - office_nodes_apps['msteams'] is defined
        - office_nodes_apps['msteams']

    - name: "Provision OBS application"
      vars:
        app_obs:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_obs"
      when:
        - office_nodes_apps['obs'] is defined
        - office_nodes_apps['obs']

    - name: "Provision ShotCut application"
      vars:
        app_shotcut:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_shotcut"
      when:
        - office_nodes_apps['shotcut'] is defined
        - office_nodes_apps['shotcut']

    - name: "Provision Skype application"
      vars:
        app_skype:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_skype"
      when:
        - office_nodes_apps['skype'] is defined
        - office_nodes_apps['skype']

    - name: "Provision Spotify application"
      vars:
        app_spotify:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_spotify"
      when:
        - office_nodes_apps['spotify'] is defined
        - office_nodes_apps['spotify']

    - name: "Provision Zoom application"
      vars:
        app_zoom:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.application.app_zoom"
      when:
        - office_nodes_apps['zoom'] is defined
        - office_nodes_apps['zoom']
...
