---
- name: "System / GUI / Cinnamon / Initialize"
  ansible.builtin.include_tasks:
    file: "sys_gui_cinnamon_initialize.yml"

- name: "System / GUI / Cinnamon / Deploy"
  ansible.builtin.include_tasks:
    file: "sys_gui_cinnamon_deploy.yml"
  when:
    - "'deploy' in sys_gui_cinnamon"
    - "sys_gui_cinnamon['deploy']"

- name: "System / GUI / Cinnamon / Finalize"
  ansible.builtin.include_tasks:
    file: "sys_gui_cinnamon_finalize.yml"
...
