---
- name: "System / GUI / Cinnamon / Provision / Configuration"
  ansible.builtin.include_tasks:
    file: "sys_gui_cinnamon_provision_configuration.yml"
  when:
    - sys_gui_cinnamon_users is defined
    - sys_gui_cinnamon_users['default'] is defined
    - sys_gui_cinnamon_users['default'] | length > 0
    - sys_gui_cinnamon_users['default'] in sys_gui_cinnamon_catalog_user
...
