---
- name: "System / GUI / Cinnamon / Provision / Configuration / Create configuration repository ({{
    sys_gui_cinnamon_base['paths']['users'] + '/' + sys_gui_cinnamon___provision_user['user'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ sys_gui_cinnamon_base['paths']['users'] + '/' + sys_gui_cinnamon___provision_user['user'] }}"
    owner: "{{ sys_gui_cinnamon_base['access']['user']['owner'] }}"
    group: "{{ sys_gui_cinnamon_base['access']['group']['owner'] }}"
    mode: "{{ sys_gui_cinnamon_base['access']['mode']['dir'] }}"

- name: "System / GUI / Cinnamon / Provision / Configuration / Create user configuration ({{
    sys_gui_cinnamon___provision_user['theme'] }})"
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ sys_gui_cinnamon_base['access']['user']['owner'] }}"
    group: "{{ sys_gui_cinnamon_base['access']['group']['owner'] }}"
    mode: "{{ sys_gui_cinnamon_base['access']['mode']['file'] }}"
    src: "{{ sys_gui_cinnamon_base['templates'][sys_gui_cinnamon___provision_user['theme']] }}"
    dest: "{{
      sys_gui_cinnamon_base['paths']['users'] + '/' +
      sys_gui_cinnamon___provision_user['user'] + '/' +
      sys_gui_cinnamon___provision_user['theme'] }}"

# - name: "System / GUI / Cinnamon / Provision / Configuration / Load user configuration"
#   vars:
#     sys_gui_cinnamon___provision_theme: "{{
#       sys_gui_cinnamon_base['paths']['users'] + '/' +
#       sys_gui_cinnamon___provision_user['user'] + '/' +
#       sys_gui_cinnamon___provision_user['theme'] }}"
#   become: true
#   changed_when: false
#   ansible.builtin.command:
#     argv:
#       - "/bin/su"
#       - "-l"
#       - "-c"
#       - "/bin/sh -c \"{{ sys_gui_cinnamon_base['run']['dconf'] }} load /org/cinnamon/ < {{ sys_gui_cinnamon___provision_theme }}\""
#       - "{{ sys_gui_cinnamon___provision_user['user'] }}"
...
