---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "stg_nfs_server"

    - name: "Identify service status"
      ansible.builtin.command:
        argv:
          - "systemctl"
          - "is-enabled"
          - "{{ stg_nfs_server_subsystems['service'] }}"
      changed_when: false
      register: result

    - name: "Check that the service is active"
      ansible.builtin.assert:
        that:
          - result['stdout_lines'] is search( 'enabled' )

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ stg_nfs_server_base['files']['X_FILE_SERVER_SETUP_X'] }}"
      register: file_stat

    - name: "Verify path is created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
