---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_shell:
          resolve_prereq: true
          deploy: true
        sys_shell_catalog:
          zsh: true
          bash: true
          ksh: true
          csh: true
      ansible.builtin.include_role:
        name: "sys_shell"
...
