---
app_keepassx_platforms:
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_keepassx_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'Fedora' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

app_keepassx_profiles_common:
  snap:
    latest:
      packages:
        - name: "keepassxc"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "org.keepassxc.KeePassXC"
...
