---
app_keepassx_platforms:
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_keepassx_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'Fedora' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

app_keepassx_profiles_common:
  snap:
    latest:
      packages:
        - name: "keepassx"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "org.keepassx.KeePassXC"

app_keepassx_base:
  paths:
    etc_keepassx: "
      {%- if app_keepassx_application['type'] == 'distro' -%}
        {{ '/.config/keepassxc' }}
      {%- endif -%}
      "
  etc:
    keepassx_ini: "
      {%- if app_keepassx_application['type'] == 'distro' -%}
        {{ '/.config/keepassxc/keepassxc.ini' }}
      {%- endif -%}
      "
  templates:
    keepassx_ini: "keepassxc.ini.j2"
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0750"
      file: "0640"
      exe: "0750"

# Temporary loop variables
# app_keepassx___prepare_path
# app_keepassx___setup_user
...
