---
- name: "System / MC / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_user: "testusr64"

  pre_tasks:
    - name: "Create test users"
      vars:
        sys_user:
          setup: true
        sys_user_accounts:
          - name: "{{ test_user }}"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_user"

  tasks:
    - name: "Example: Install MC tool and deploy default user configuration"
      vars:
        sys_mc:
          resolve_prereq: true
          deploy: true
          setup: true
        sys_mc_users:
          - name: "{{ test_user }}"
            group: "{{ test_user }}"
            home: "/home/{{ test_user }}"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_mc"
...
