---
- name: "System / Repository / Deploy / Distro"
  include_tasks:
    file: "{{ 'sys_repository_deploy_distro.yml' }}"
  when:
    - sys_repository_packages['distro'] | length > 0

- name: "System / Repository / Deploy / Tools"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_tools.yml"

- name: "System / Repository / Deploy / FlatPak"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_flatpak.yml"
  when:
    - "'flatpak' in sys_repository_managers"
    - sys_repository_managers['flatpak']

- name: "System / Repository / Deploy / Snap"
  ansible.builtin.include_tasks:
    file: "{{ 'sys_repository_deploy_snap-' + sys_repository_os_family + '.yml' }}"
  when:
    - "'snap' in sys_repository_managers"
    - sys_repository_managers['snap']

- name: "System / Repository / Deploy / GIT"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_git.yml"
  when:
    - "'git' in sys_repository_managers"
    - sys_repository_managers['git']

- name: "System / Repository / Deploy / PIP"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_pip.yml"
  when:
    - "'pip' in sys_repository_managers"
    - sys_repository_managers['pip']
...
