---
name: "Test / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"
      - "develop"
      - "main"

jobs:
  test_batscore_alpine_3:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/devap-lib"

      - name: "Build app"
        run: "./bin/devap-build -i"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e alpine-3-bash-test:latest"
...
